In [1]:
# Importing necessary modules to clean and merge data
import numpy as np
import pandas as pd

In [2]:
crime2015 = pd.read_excel('crime2015.xls', header=0)

In [3]:
#fillna with the value of the row before it
crime2015.fillna(method = 'ffill', inplace = True)
crime2015.head()

,State,Area,Unnamed: 2,Population,Violent crime1,Murder and nonnegligent manslaughter,Rape (revised definition)2,Rape (legacy definition)3,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft
0,ALABAMA,Metropolitan Statistical Area,NaN,3708033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ALABAMA,Metropolitan Statistical Area,Area actually reporting,0.971,18122,283,1496.0,1080.0,4080,12263,113447,27208,78141.0,8098.0
2,ALABAMA,Metropolitan Statistical Area,Estimated total,1,18500,287,1537.0,1111.0,4138,12538,115920,27852,79799.0,8269.0
3,ALABAMA,Cities outside metropolitan areas,Estimated total,522241,18500,287,1537.0,1111.0,4138,12538,115920,27852,79799.0,8269.0
4,ALABAMA,Cities outside metropolitan areas,Area actually reporting,0.974,3178,32,311.0,218.0,354,2481,20873,4438,15106.0,1329.0

In [4]:
#Delete all rows except for the ones that contain state total
crime2015[crime2015['Area'] == 'State Total']
crime2015.reset_index(drop = True)

,State,Area,Unnamed: 2,Population,Violent crime1,Murder and nonnegligent manslaughter,Rape (revised definition)2,Rape (legacy definition)3,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft
0,ALABAMA,Metropolitan Statistical Area,NaN,3708033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ALABAMA,Metropolitan Statistical Area,Area actually reporting,0.971,18122,283,1496.0,1080.0,4080,12263,113447,27208,78141.0,8098.0
2,ALABAMA,Metropolitan Statistical Area,Estimated total,1,18500,287,1537.0,1111.0,4138,12538,115920,27852,79799.0,8269.0
3,ALABAMA,Cities outside metropolitan areas,Estimated total,522241,18500,287,1537.0,1111.0,4138,12538,115920,27852,79799.0,8269.0
4,ALABAMA,Cities outside metropolitan areas,Area actually reporting,0.974,3178,32,311.0,218.0,354,2481,20873,4438,15106.0,1329.0
5,ALABAMA,Cities outside metropolitan areas,Estimated total,1,3240,33,315.0,222.0,360,2532,21203,4518,15329.0,1356.0
6,ALABAMA,Nonmetropolitan counties,Estimated total,628705,3240,33,315.0,222.0,360,2532,21203,4518,15329.0,1356.0
7,ALABAMA,Nonmetropolitan counties,Area actually reporting,0.994,1205,28,186.0,122.0,112,879,7578,2868,4004.0,706.0
8,ALABAMA,Nonmetropolitan counties,Estimated total,1,1212,28,187.0,123.0,113,884,7623,2885,4028.0,710.0
9,ALABAMA,State Total,Estimated total,4858979,22952,348,2039.0,1456.0,4611,15954,144746,35255,99156.0,10335.0
10,ALABAMA,State Total,"Rate per 100,000 inhabitants",4858979,472.4,7.2,42.0,30.0,94.9,328.3,2978.9,725.6,2040.7,212.7
11,ALASKA,Metropolitan Statistical Area,"Rate per 100,000 inhabitants",351857,472.4,7.2,42.0,30.0,94.9,328.3,2978.9,725.6,2040.7,212.7
12,ALASKA,Metropolitan Statistical Area,Area actually reporting,1,3464,27,541.0,401.0,658,2238,14151,1919,10884.0,1348.0
13,ALASKA,Cities outside metropolitan areas,Area actually reporting,127499,3464,27,541.0,401.0,658,2238,14151,1919,10884.0,1348.0
14,ALASKA,Cities outside metropolitan areas,Area actually reporting,0.972,886,10,178.0,128.0,60,638,3523,530,2737.0,256.0
15,ALASKA,Cities outside metropolitan areas,Estimated total,1,913,10,184.0,133.0,62,657,3625,545,2817.0,263.0
16,ALASKA,Nonmetropolitan counties,Estimated total,259076,913,10,184.0,133.0,62,657,3625,545,2817.0,263.0
17,ALASKA,Nonmetropolitan counties,Area actually reporting,1,1015,22,176.0,116.0,41,776,3030,1047,1548.0,435.0
18,ALASKA,State Total,Area actually reporting,738432,5392,59,901.0,650.0,761,3671,20806,3511,15249.0,2046.0
19,ALASKA,State Total,"Rate per 100,000 inhabitants",738432,730.2,8,122.0,88.0,103.1,497.1,2817.6,475.5,2065.1,277.1
20,ARIZONA,Metropolitan Statistical Area,"Rate per 100,000 inhabitants",6479810,730.2,8,122.0,88.0,103.1,497.1,2817.6,475.5,2065.1,277.1
21,ARIZONA,Metropolitan Statistical Area,Area actually reporting,0.997,24725,280,2805.0,2072.0,6239,15401,198411,35919,146431.0,16061.0
22,ARIZONA,Metropolitan Statistical Area,Estimated total,1,24781,280,2811.0,2077.0,6251,15439,198994,36015,146882.0,16097.0
23,ARIZONA,Cities outside metropolitan areas,,124240,24781,,2811.0,2077.0,6251,15439,198994,36015,146882.0,16097.0
24,ARIZONA,Cities outside metropolitan areas,Area actually reporting,0.939,2678,24,269.0,199.0,91,2294,5854,1280,4095.0,479.0
25,ARIZONA,Cities outside metropolitan areas,Estimated total,1,2851,26,286.0,210.0,97,2442,6233,1363,4360.0,510.0
26,ARIZONA,Nonmetropolitan counties,,224015,2851,26,286.0,210.0,97,2442,6233,1363,4360.0,510.0
27,ARIZONA,Nonmetropolitan counties,Area actually reporting,1,380,3,11.0,7.0,12,354,1880,579,1123.0,178.0
28,ARIZONA,State Total,Area actually reporting,6828065,28012,309,3108.0,2294.0,6360,18235,207107,37957,152365.0,16785.0
29,ARIZONA,State Total,"Rate per 100,000 inhabitants",6828065,410.2,4.5,45.5,33.6,93.1,267.1,3033.2,555.9,2231.5,245.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,WEST VIRGINIA,Metropolitan Statistical Area,Area actually reporting,0.898,3557,45,402.0,245.0,625,2485,25404,6476,17423.0,1505.0
473,WEST VIRGINIA,Metropolitan Statistical Area,Estimated total,1,3887,47,433.0,269.0,667,2740,28418,7019,19731.0,1668.0
474,WEST VIRGINIA,Cities outside metropolitan areas,Estimated total,189216,3887,47,433.0,269.0,667,2740,28418,7019,19731.0,1668.0
475,WEST VIRGINIA,Cities outside metropolitan areas,Area actually reporting,0.53,280,4,23.0,18.0,28,225,1619,264,1285.0,70.0
476,WEST VIRGINIA,Cities outside metropolitan areas,Estimated total,1,519,8,33.0,26.0,53,425,3056,498,2426.0,132.0
477,WEST VIRGINIA,Nonmetropolitan counties,Estimated total,518050,519,8,33.0,26.0,53,425,3056,498,2426.0,132.0
478,WEST VIRGINIA,Nonmetropolitan counties,Area actually reporting,0.731,1325,11,142.0,83.0,29,1143,4223,1208,2694.0,321.0
479,WEST VIRGINIA,Nonmetropolitan counties,Estimated total,1,1825,15,206.0,125.0,40,1564,5777,1653,3685.0,439.0
480,WEST VIRGINIA,State Total,Estimated total,1844128,6231,70,672.0,420.0,760,4729,37251,9170,25842.0,2239.0
481,WEST VIRGINIA,State Total,"Rate per 100,000 inhabitants",1844128,337.9,3.8,36.4,22.8,41.2,256.4,2020,497.3,1401.3,121.4
482,WISCONSIN6,Metropolitan Statistical Area,"Rate per 100,000 inhabitants",4268682,337.9,3.8,36.4,22.8,41.2,256.4,2020,497.3,1401.3,121.4
483,WISCONSIN7,Metropolitan Statistical Area,Area actually reporting,0.965,15597,207,1368.0,923.0,5087,8935,88714,15012,63592.0,10110.0
484,WISCONSIN8,Metropolitan Statistical Area,Estimated total,1,15770,209,1396.0,945.0,5131,9034,91251,15314,65713.0,10224.0
485,WISCONSIN9,Cities outside metropolitan areas,Estimated total,639613,15770,209,1396.0,945.0,5131,9034,91251,15314,65713.0,10224.0
486,WISCONSIN10,Cities outside metropolitan areas,Area actually reporting,0.938,1015,9,189.0,141.0,79,738,14140,1732,12065.0,343.0
487,WISCONSIN11,Cities outside metropolitan areas,Estimated total,1,1082,10,201.0,150.0,84,787,15070,1846,12858.0,366.0
488,WISCONSIN12,Nonmetropolitan counties,Estimated total,863042,1082,10,201.0,150.0,84,787,15070,1846,12858.0,366.0
489,WISCONSIN13,Nonmetropolitan counties,Area actually reporting,1,795,21,183.0,129.0,17,574,7603,2394,4814.0,395.0
490,WISCONSIN14,State Total,Area actually reporting,5771337,17647,240,1780.0,1224.0,5232,10395,113924,19554,83385.0,10985.0
491,WISCONSIN15,State Total,"Rate per 100,000 inhabitants",5771337,305.8,4.2,30.8,21.2,90.7,180.1,1974,338.8,1444.8,190.3
492,WYOMING,Metropolitan Statistical Area,"Rate per 100,000 inhabitants",179738,,4.2,30.8,21.2,90.7,180.1,,338.8,1444.8,190.3
493,WYOMING,Metropolitan Statistical Area,Area actually reporting,1,366,8,50.0,36.0,31,277,4584,763,3579.0,242.0
494,WYOMING,Cities outside metropolitan areas,Area actually reporting,245549,366,8,50.0,36.0,31,277,4584,763,3579.0,242.0
495,WYOMING,Cities outside metropolitan areas,Area actually reporting,0.967,629,5,82.0,62.0,24,518,5255,693,4313.0,249.0
496,WYOMING,Cities outside metropolitan areas,Estimated total,1,649,5,83.0,63.0,25,536,5434,717,4460.0,257.0
497,WYOMING,Nonmetropolitan counties,Estimated total,160820,649,,83.0,63.0,,536,5434,717,4460.0,257.0
498,WYOMING,Nonmetropolitan counties,Area actually reporting,0.916,262,3,35.0,23.0,3,221,1038,258,695.0,85.0
499,WYOMING,Nonmetropolitan counties,Estimated total,1,287,3,40.0,26.0,3,241,1133,282,758.0,93.0
500,WYOMING,State Total,Estimated total,586107,1302,16,173.0,125.0,59,1054,11151,1762,8797.0,592.0
501,WYOMING,State Total,"Rate per 100,000 inhabitants",586107,222.1,2.7,29.5,21.3,10.1,179.8,1902.6,300.6,1500.9,101.0

In [5]:
#import data from other years:
crime2014 = pd.read_excel('crime2014.xls', header=0)
crime2013 = pd.read_excel('crime2013.xls', header=0)
crime2012 = pd.read_excel('crime2012.xls', header=0)
crime2011 = pd.read_excel('crime2011.xls', header=0)
crime2010 = pd.read_excel('crime2010.xls', header=0)

## Automate cleaning for each excel data set:

In [6]:
def clean(df):
    #fill na values with the value of the row above 
    df.fillna(method = 'ffill', inplace = True)
    #select the rows where the column 'Area' = 'State Total'
    df = df[df['Area'] == 'State Total']
    #return cleaned table with index reset to 0 start
    return df.reset_index(drop=True).head()

In [7]:
clean(crime2010)

,State,Area,Unnamed: 2,Population,Violent crime,Murder and nonnegligent manslaughter,Forcible rape,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Unnamed: 13
0,ALABAMA,State Total,Estimated total,4779736,18056,273,1349,4761,11673,168092,42034,115458.0,10600.0,
1,ALABAMA,State Total,"Rate per 100,000 inhabitants",4779736,377.8,5.7,28.2,99.6,244.2,3516.8,879.4,2415.6,221.8,
2,ALASKA,State Total,Area actually reporting,710231,4537,31,533,594,3379,20259,3105,15535.0,1619.0,
3,ALASKA,State Total,"Rate per 100,000 inhabitants",710231,638.8,4.4,75,83.6,475.8,2852.5,437.2,2187.3,228.0,
4,ARIZONA,State Total,Estimated total,6392017,26085,409,2165,6937,16574,225893,50771,153614.0,21508.0,

In [8]:
clean(crime2011)

,State,Area,Unnamed: 2,Population,Violent crime,Murder and nonnegligent manslaughter,Forcible rape,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft
0,ALABAMA1,State Total,Estimated total,4802740,20174,301,1371,4910,13592,173190,51117,111411.0,10662.0
1,ALABAMA1,State Total,"Rate per 100,000 inhabitants",4802740,420.1,6.3,28.5,102.2,283,3606.1,1064.3,2319.7,222.0
2,ALASKA,State Total,Area actually reporting,722718,4383,29,420,576,3358,19028,2826,14859.0,1343.0
3,ALASKA,State Total,"Rate per 100,000 inhabitants",722718,606.5,4,58.1,79.7,464.6,2632.8,391,2056.0,185.8
4,ARIZONA,State Total,Estimated total,6482505,26311,405,2264,7127,16515,230422,54929,155664.0,19829.0

In [9]:
clean(crime2012)

,State,Area,Unnamed: 2,Population,Violent crime,Murder and nonnegligent manslaughter,Forcible rape,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft
0,ALABAMA,State Total,Estimated total,4822023,21693,342,1296,5020,15035,168878,47481,111523.0,9874.0
1,ALABAMA,State Total,"Rate per 100,000 inhabitants",4822023,449.9,7.1,26.9,104.1,311.8,3502.2,984.7,2312.8,204.8
2,ALASKA,State Total,Area actually reporting,731449,4412,30,583,630,3169,20037,2950,15565.0,1522.0
3,ALASKA,State Total,"Rate per 100,000 inhabitants",731449,603.2,4.1,79.7,86.1,433.2,2739.4,403.3,2128.0,208.1
4,ARIZONA,State Total,Area actually reporting,6553255,28108,358,2277,7386,18087,231930,52934,159838.0,19158.0

In [10]:
clean(crime2013)

,State,Area,Unnamed: 2,Population,Violent crime1,Murder and nonnegligent manslaughter,Rape (revised definition)2,Rape (legacy definition)3,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft
0,ALABAMA4,State Total,Estimated total,4833722,20826,347,2044.0,1428.0,4648,13787,161993,42429,108993.0,10571.0
1,ALABAMA4,State Total,"Rate per 100,000 inhabitants",4833722,430.8,7.2,42.3,29.5,96.2,285.2,3351.3,877.8,2254.8,218.7
2,ALASKA4,State Total,Area actually reporting,735132,4708,34,922.0,644.0,624,3128,21210,2916,16599.0,1695.0
3,ALASKA4,State Total,"Rate per 100,000 inhabitants",735132,640.4,4.6,125.4,87.6,84.9,425.5,2885.2,396.7,2258.0,230.6
4,"ARIZONA5,6",State Total,Area actually reporting,6626624,27599,357,3050.0,2343.0,6702,17490,225243,48533,159272.0,17438.0

In [11]:
clean(crime2014)

,State,Area,Unnamed: 2,Population,Violent crime1,Murder and nonnegligent manslaughter,Rape (revised definition)2,Rape (legacy definition)3,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft
0,ALABAMA4,State Total,Estimated total,4849377,20727,276,2005.0,1436.0,4701,13745,154094,39715,104238.0,10141.0
1,ALABAMA4,State Total,"Rate per 100,000 inhabitants",4849377,427.4,5.7,41.3,29.6,96.9,283.4,3177.6,819,2149.5,209.1
2,ALASKA4,State Total,Area actually reporting,736732,4684,41,771.0,555.0,629,3243,20334,3150,15445.0,1739.0
3,ALASKA4,State Total,"Rate per 100,000 inhabitants",736732,635.8,5.6,104.7,75.3,85.4,440.2,2760,427.6,2096.4,236.0
4,ARIZONA4,State Total,Area actually reporting,6731484,26916,319,3378.0,2464.0,6249,16970,215240,43562,154091.0,17587.0

,State,Area,Unnamed: 2,Population,Violent crime1,Murder and nonnegligent manslaughter,Rape (revised definition)2,Rape (legacy definition)3,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft
0,ALABAMA4,Metropolitan Statistical Area,NaN,3692100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ALABAMA4,Metropolitan Statistical Area,Area actually reporting,0.955,16204,232,1435.0,1033.0,4131,10406,118226,29903,80430.0,7893.0
2,ALABAMA4,Metropolitan Statistical Area,Estimated total,1,16702,236,1494.0,1076.0,4228,10744,122299,31007,83126.0,8166.0
3,ALABAMA4,Cities outside metropolitan areas,Estimated total,529129,16702,236,1494.0,1076.0,4228,10744,122299,31007,83126.0,8166.0
4,ALABAMA4,Cities outside metropolitan areas,Area actually reporting,0.933,2605,17,294.0,214.0,363,1931,21747,5005,15516.0,1226.0
5,ALABAMA4,Cities outside metropolitan areas,Estimated total,1,2769,18,310.0,226.0,386,2055,23058,5330,16420.0,1308.0
6,ALABAMA4,Nonmetropolitan counties,Estimated total,628148,2769,18,310.0,226.0,386,2055,23058,5330,16420.0,1308.0
7,ALABAMA4,Nonmetropolitan counties,Area actually reporting,0.994,1247,22,199.0,133.0,86,940,8683,3357,4663.0,663.0
8,ALABAMA4,Nonmetropolitan counties,Estimated total,1,1256,22,201.0,134.0,87,946,8737,3378,4692.0,667.0
9,ALABAMA4,State Total,Estimated total,4849377,20727,276,2005.0,1436.0,4701,13745,154094,39715,104238.0,10141.0
10,ALABAMA4,State Total,"Rate per 100,000 inhabitants",4849377,427.4,5.7,41.3,29.6,96.9,283.4,3177.6,819,2149.5,209.1
11,ALASKA4,Metropolitan Statistical Area,"Rate per 100,000 inhabitants",351408,427.4,5.7,41.3,29.6,96.9,283.4,3177.6,819,2149.5,209.1
12,ALASKA4,Metropolitan Statistical Area,Area actually reporting,1,2899,17,442.0,329.0,557,1883,13905,1626,11148.0,1131.0
13,ALASKA4,Cities outside metropolitan areas,Area actually reporting,128681,2899,17,442.0,329.0,557,1883,13905,1626,11148.0,1131.0
14,ALASKA4,Cities outside metropolitan areas,Area actually reporting,0.966,722,3,128.0,93.0,45,546,3362,413,2702.0,247.0
15,ALASKA4,Cities outside metropolitan areas,Estimated total,1,748,3,133.0,98.0,47,565,3480,427,2797.0,256.0
16,ALASKA4,Nonmetropolitan counties,Estimated total,256643,748,3,133.0,98.0,47,565,3480,427,2797.0,256.0
17,ALASKA4,Nonmetropolitan counties,Area actually reporting,1,1037,21,196.0,128.0,25,795,2949,1097,1500.0,352.0
18,ALASKA4,State Total,Area actually reporting,736732,4684,41,771.0,555.0,629,3243,20334,3150,15445.0,1739.0
19,ALASKA4,State Total,"Rate per 100,000 inhabitants",736732,635.8,5.6,104.7,75.3,85.4,440.2,2760,427.6,2096.4,236.0
20,ARIZONA4,Metropolitan Statistical Area,"Rate per 100,000 inhabitants",6382968,635.8,5.6,104.7,75.3,85.4,440.2,2760,427.6,2096.4,236.0
21,ARIZONA4,Metropolitan Statistical Area,Area actually reporting,0.981,24006,288,2762.0,2024.0,6117,14839,201780,39504,146202.0,16074.0
22,ARIZONA4,Metropolitan Statistical Area,Estimated total,1,24291,293,2791.0,2045.0,6155,15052,204214,40034,147926.0,16254.0
23,ARIZONA4,Cities outside metropolitan areas,,123617,24291,,2791.0,2045.0,6155,15052,204214,40034,147926.0,16254.0
24,ARIZONA4,Cities outside metropolitan areas,Area actually reporting,0.784,1721,20,452.0,323.0,55,1194,7020,2111,3996.0,913.0
25,ARIZONA4,Cities outside metropolitan areas,Estimated total,1,2192,25,574.0,409.0,70,1523,8952,2692,5096.0,1164.0
26,ARIZONA4,Nonmetropolitan counties,,224899,2192,25,574.0,409.0,70,1523,8952,2692,5096.0,1164.0
27,ARIZONA4,Nonmetropolitan counties,Area actually reporting,1,433,1,13.0,10.0,24,395,2074,836,1069.0,169.0
28,ARIZONA4,State Total,Area actually reporting,6731484,26916,319,3378.0,2464.0,6249,16970,215240,43562,154091.0,17587.0
29,ARIZONA4,State Total,"Rate per 100,000 inhabitants",6731484,399.9,4.7,50.2,36.6,92.8,252.1,3197.5,647.1,2289.1,261.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,WEST VIRGINIA4,Metropolitan Statistical Area,Area actually reporting,0.928,3310,44,333.0,175.0,530,2403,26935,6481,19081.0,1373.0
476,WEST VIRGINIA4,Metropolitan Statistical Area,Estimated total,1,3526,46,348.0,187.0,560,2572,29155,6857,20830.0,1468.0
477,WEST VIRGINIA4,Cities outside metropolitan areas,Estimated total,190438,3526,46,348.0,187.0,560,2572,29155,6857,20830.0,1468.0
478,WEST VIRGINIA4,Cities outside metropolitan areas,Area actually reporting,0.582,425,6,29.0,22.0,29,361,2211,385,1764.0,62.0
479,WEST VIRGINIA4,Cities outside metropolitan areas,Estimated total,1,721,10,41.0,33.0,50,620,3801,662,3032.0,107.0
480,WEST VIRGINIA4,Nonmetropolitan counties,Estimated total,521158,721,10,41.0,33.0,50,620,3801,662,3032.0,107.0
481,WEST VIRGINIA4,Nonmetropolitan counties,Area actually reporting,0.896,1197,16,99.0,54.0,37,1045,4205,1303,2614.0,288.0
482,WEST VIRGINIA4,Nonmetropolitan counties,Estimated total,1,1341,18,116.0,65.0,41,1166,4692,1454,2917.0,321.0
483,WEST VIRGINIA4,State Total,Estimated total,1850326,5588,74,505.0,285.0,651,4358,37648,8973,26779.0,1896.0
484,WEST VIRGINIA4,State Total,"Rate per 100,000 inhabitants",1850326,302,4,27.3,15.4,35.2,235.5,2034.7,484.9,1447.3,102.5
485,WISCONSIN5,Metropolitan Statistical Area,"Rate per 100,000 inhabitants",4251567,302,4,27.3,15.4,35.2,235.5,2034.7,484.9,1447.3,102.5
486,WISCONSIN5,Metropolitan Statistical Area,Area actually reporting,0.967,14725,142,1232.0,851.0,4918,8433,95066,16637,69341.0,9088.0
487,WISCONSIN5,Metropolitan Statistical Area,Estimated total,1,14890,143,1259.0,872.0,4961,8527,97688,16979,71524.0,9185.0
488,WISCONSIN5,Cities outside metropolitan areas,Estimated total,637105,14890,143,1259.0,872.0,4961,8527,97688,16979,71524.0,9185.0
489,WISCONSIN5,Cities outside metropolitan areas,Area actually reporting,0.952,1019,11,214.0,163.0,73,721,14099,1715,12054.0,330.0
490,WISCONSIN5,Cities outside metropolitan areas,Estimated total,1,1072,12,226.0,172.0,77,757,14813,1802,12664.0,347.0
491,WISCONSIN5,Nonmetropolitan counties,Estimated total,868892,1072,12,226.0,172.0,77,757,14813,1802,12664.0,347.0
492,WISCONSIN5,Nonmetropolitan counties,Area actually reporting,1,752,10,189.0,124.0,28,525,7737,2435,4915.0,387.0
493,WISCONSIN5,State Total,Area actually reporting,5757564,16714,165,1674.0,1168.0,5066,9809,120238,21216,89103.0,9919.0
494,WISCONSIN5,State Total,"Rate per 100,000 inhabitants",5757564,290.3,2.9,29.1,20.3,88,170.4,2088.3,368.5,1547.6,172.3
495,WYOMING4,Metropolitan Statistical Area,"Rate per 100,000 inhabitants",178196,,2.9,29.1,20.3,88,170.4,,368.5,1547.6,172.3
496,WYOMING4,Metropolitan Statistical Area,Area actually reporting,1,305,6,37.0,25.0,30,232,4292,733,3356.0,203.0
497,WYOMING4,Cities outside metropolitan areas,Area actually reporting,246602,305,6,37.0,25.0,30,232,4292,733,3356.0,203.0
498,WYOMING4,Cities outside metropolitan areas,Area actually reporting,0.974,580,6,80.0,61.0,18,476,5806,707,4816.0,283.0
499,WYOMING4,Cities outside metropolitan areas,Estimated total,1,594,6,81.0,62.0,18,489,5962,726,4945.0,291.0
500,WYOMING4,Nonmetropolitan counties,Estimated total,159355,594,,81.0,62.0,,489,5962,726,4945.0,291.0
501,WYOMING4,Nonmetropolitan counties,Area actually reporting,0.918,222,4,50.0,35.0,5,163,1123,211,812.0,100.0
502,WYOMING4,Nonmetropolitan counties,Estimated total,1,243,4,56.0,39.0,5,178,1223,230,884.0,109.0
503,WYOMING4,State Total,Estimated total,584153,1142,16,174.0,126.0,53,899,11477,1689,9185.0,603.0
504,WYOMING4,State Total,"Rate per 100,000 inhabitants",584153,195.5,2.7,29.8,21.6,9.1,153.9,1964.7,289.1,1572.4,103.2

In [12]:
#read in new table and drop all nan values
grads = pd.read_excel('gradrates.xls')
grads.dropna(how='any', inplace=True)

In [16]:
#Select only graduation rates for each state and the national average.
grad = grads.iloc[:, [0,1,2,3,4]]
grad.head()

              2010-11 2011-12 2012-13  2013-14  2014-15
United States      79      80    81.4     82.3     83.2
Alabama            72      75      80     86.3     89.3
Alaska             68      70    71.8     71.1     75.6
Arizona            78      76    75.1     75.7     77.4
Arkansas           81      84    84.9     86.9     84.9